name: Container Cleaner
description: Delete old container images from GitHub Container Registry (optimized for container-builder)

inputs:
  token:
    description: 'GitHub token for authentication (needs packages:delete permission)'
    required: true
  image-name:
    description: 'Name of the image (e.g. service-name)'
    required: true
  pr-retention-days:
    description: 'Delete PR tags older than this many days'
    required: false
    default: '14'
  dry-run:
    description: 'Show what would be deleted without actually deleting'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # Step 1: Clean old PR tags (pr-*, older than retention days)
    # Regex: ^pr- matches tags starting with "pr-" (e.g., pr-123)
    # Excludes: latest, version tags (v1.2.3, v1.2.202501012230, v2.0.0-beta, etc.)
    - name: Clean old PR tags
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        token: ${{ inputs.token }}
        package: monorepo/${{ inputs.image-name }}
        delete-tags: ^pr-
        older-than: ${{ inputs.pr-retention-days }} days
        exclude-tags: ^(latest|v\d+\.\d+\.\d+.*)$
        use-regex: true
        dry-run: ${{ inputs.dry-run }}
        validate: true

    # Step 2: Clean all SHA tags (sha-*, regardless of age)
    # Regex: ^sha- matches tags starting with "sha-" (e.g., sha-1234abc)
    # Excludes: latest, version tags (v1.2.3, v1.2.202501012230, v2.0.0-beta, etc.)
    - name: Clean SHA tags
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        token: ${{ inputs.token }}
        package: monorepo/${{ inputs.image-name }}
        delete-tags: ^sha-
        exclude-tags: ^(latest|v\d+\.\d+\.\d+.*)$
        use-regex: true
        dry-run: ${{ inputs.dry-run }}
        validate: true

    # Step 3: Clean all untagged images
    # Excludes: latest, version tags (v1.2.3, v1.2.202501012230, v2.0.0-beta, etc.)
    - name: Clean untagged images
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        token: ${{ inputs.token }}
        package: monorepo/${{ inputs.image-name }}
        keep-n-untagged: 0
        exclude-tags: ^(latest|v\d+\.\d+\.\d+.*)$
        use-regex: true
        dry-run: ${{ inputs.dry-run }}
        validate: true
