stacks:
  - name: terragrunt
    id: aws
    paths:
      - "dystopia/{service}/aws/{environment}"
      - "system-components/{service}/infrastructure/aws/{environment}"
    environments:
      develop:
        aws_region: ap-northeast-1
        iam_role_plan: arn:aws:iam::123456789012:role/aws-plan-develop-role
        iam_role_apply: arn:aws:iam::123456789012:role/aws-apply-develop-role
      staging:
        aws_region: ap-northeast-1
        iam_role_plan: arn:aws:iam::123456789012:role/aws-plan-staging-role
        iam_role_apply: arn:aws:iam::123456789012:role/aws-apply-staging-role
      production:
        aws_region: ap-northeast-1
        iam_role_plan: arn:aws:iam::123456789012:role/aws-plan-production-role
        iam_role_apply: arn:aws:iam::123456789012:role/aws-apply-production-role
    exclude:
      - service: demo
  - name: container
    paths:
      - "dystopia/{service}"
      - "system-components/{service}"
    attributes:
      repository: registry.example.com/{service}
    exclude:
      - service: demo
  - name: kubernetes
    paths:
      - "dystopia/{service}/kubernetes/overlays/{environment}"
      - "system-components/{service}/kubernetes/overlays/{environment}"
    environments:
      develop:
        namespace: default
      staging:
        namespace: default
      production:
        namespace: default
    exclude:
      - service: demo
