name: 'FluxCD Manifest Generator (Ruby)'
description: 'Generate FluxCD manifests using Clean Architecture Ruby implementation'
author: 'panicboat'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token with contents: write permission'
    required: true
  environments:
    description: 'Target environments (comma-separated)'
    required: false
    default: 'develop,staging,production'
  repository-owner:
    description: 'GitHub repository owner'
    required: false
    default: 'panicboat'
  repository-name:
    description: 'GitHub repository name'
    required: false
    default: 'generated-manifests'

runs:
  using: 'composite'
  steps:
    - name: Checkout deploy-actions
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        repository: panicboat/deploy-actions
        path: deploy-actions

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.5'
        bundler-cache: true
        working-directory: deploy-actions/flux-generator

    - name: Generate FluxCD manifests
      id: generate
      shell: bash
      working-directory: ${{ github.workspace }}/deploy-actions/flux-generator
      env:
        RESOURCE_NAME: ${{ inputs.repository-name }}
        ENVIRONMENTS: ${{ inputs.environments }}
        OUTPUT_DIR: ${{ github.workspace }}/${{ inputs.repository-name }}
      run: |
        ENVS=$(echo "$ENVIRONMENTS" | tr ',' ' ')
        bundle exec ruby bin/generator generate --resource-name $RESOURCE_NAME --environments $ENVS --output-dir $OUTPUT_DIR
