name: 'FluxCD Manifest Generator (Ruby)'
description: 'Generate FluxCD manifests using Clean Architecture Ruby implementation'
author: 'panicboat'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  environments:
    description: 'Target environments (comma-separated)'
    required: false
    default: 'develop,staging,production'
  github-token:
    description: 'GitHub token with contents: write permission'
    required: true
  target-path:
    description: 'Target path for generated manifests'
    required: true
  deploy-actions-repository:
    description: 'Deploy actions repository to use'
    required: false
    default: 'panicboat/deploy-actions'

runs:
  using: 'composite'
  steps:
    - name: Checkout deploy-actions
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.deploy-actions-repository }}
        path: deploy-actions

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.4'
        bundler-cache: true
        working-directory: deploy-actions/flux-generator

    - name: Generate FluxCD manifests
      id: generate
      shell: bash
      working-directory: ${{ github.workspace }}/deploy-actions/flux-generator
      env:
        ENVIRONMENTS: ${{ inputs.environments }}
        TARGET_PATH: ${{ inputs.target-path }}
      run: |
        ENVS=$(echo "$ENVIRONMENTS" | tr ',' ' ')
        bundle exec ruby bin/generator generate --environments $ENVS --target-dir $TARGET_PATH
