source 'https://rubygems.org'

ruby '3.4.5'

gem 'dry-container', '~> 0.11'
gem 'dry-auto_inject', '~> 1.0'
gem 'dry-validation', '~> 1.10'
gem 'dry-struct', '~> 1.6'
gem 'thor', '~> 1.3'
gem 'yaml', '~> 0.3'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.57'
  gem 'pry', '~> 0.14'
  gem 'simplecov', '~> 0.22'
end
