name: Container Builder
description: Build and push container images to GitHub Container Registry

inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
  image-name:
    description: 'Name of the image (e.g. service-name)'
    required: true
  platforms:
    description: 'Target platforms for the Docker image'
    required: false
    default: 'linux/amd64,linux/arm64'
  working-directory:
    description: 'Directory containing the Dockerfile'
    required: false
    default: '.'
  dockerfile-path:
    description: 'Path to Dockerfile relative to working-directory'
    required: false
    default: 'Dockerfile'
  tags-template:
    description: 'Additional Docker tags template to append to defaults (see docker/metadata-action for syntax)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2
      with:
        token: ${{ inputs.token }}

    - name: Log in to the Container registry
      uses: docker/login-action@v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.12.0

    - name: Prepare tags template
      id: prepare-tags
      shell: bash
      run: |
        DEFAULT_TAGS="type=sha
        type=ref,event=pr
        type=raw,value=latest,enable={{is_default_branch}}"

        if [ -n "${{ inputs.tags-template }}" ]; then
          MERGED_TAGS="$DEFAULT_TAGS
        ${{ inputs.tags-template }}"
        else
          MERGED_TAGS="$DEFAULT_TAGS"
        fi

        echo "tags<<EOF" >> $GITHUB_OUTPUT
        echo "$MERGED_TAGS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.10.0
      with:
        images: ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
        tags: ${{ steps.prepare-tags.outputs.tags }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        platforms: ${{ inputs.platforms }}
        context: ${{ inputs.working-directory }}
        file: ${{ inputs.working-directory }}/${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
