name: check

on:
  pull_request:
    paths:
      - 'action-scripts/**'
      - 'label-dispatcher/**'
      - 'label-resolver/**'
      - '.github/workflows/check.yaml'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: action-scripts

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version-file: action-scripts/.ruby-version
          bundler-cache: true
          working-directory: action-scripts
      - run: bundle exec rspec

  validate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version-file: action-scripts/.ruby-version
          bundler-cache: true
          working-directory: action-scripts
      - run: bundle exec ruby config-manager/bin/config-manager validate
