name: check

on:
  pull_request:
    paths:
      - 'action-scripts/**'
      - 'label-dispatcher/**'
      - 'label-resolver/**'
      - '.github/workflows/check.yaml'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: action-scripts

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version-file: action-scripts/.ruby-version
          bundler-cache: true
          working-directory: action-scripts
      - run: bundle exec rspec

  validate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version-file: action-scripts/.ruby-version
          bundler-cache: true
          working-directory: action-scripts
      - run: bundle exec ruby config-manager/bin/config-manager validate
