name: 'Reusable Label Dispatcher'

on:
  workflow_call:
    inputs:
      pr-number:
        description: 'Pull request number'
        required: true
        type: string
      repository:
        description: 'Repository name (owner/repo)'
        required: true
        type: string
      config-path:
        description: 'Path to workflow configuration file'
        required: false
        type: string
        default: '.github/config/workflow-config.yaml'
    secrets:
      github-token:
        description: 'GitHub token with pull-requests: write permission'
        required: true

jobs:
  dispatch-labels:
    name: 'Dispatch Labels'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy-actions
        uses: actions/checkout@v4

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.github-token }}
          path: source-repo
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
          working-directory: scripts

      - name: Copy configuration from source repository
        run: |
          echo "📋 Copying configuration from source repository"
          echo "Source path: source-repo/${{ inputs.config-path }}"
          echo "Target path: scripts/shared/workflow-config.yaml"
          
          if [ ! -f "source-repo/${{ inputs.config-path }}" ]; then
            echo "::error::Configuration file not found: ${{ inputs.config-path }}"
            exit 1
          fi
          
          cp "source-repo/${{ inputs.config-path }}" scripts/shared/workflow-config.yaml
          echo "✅ Configuration copied successfully"

      - name: Validate configuration
        working-directory: scripts
        run: |
          echo "🔍 Validating configuration file"
          bundle exec ruby config-manager/bin/config-manager validate
        env:
          WORKFLOW_CONFIG_PATH: shared/workflow-config.yaml

      - name: Dispatch labels
        working-directory: scripts
        run: |
          echo "🚀 Starting label dispatch for PR #${{ inputs.pr-number }}"
          bundle exec ruby label-dispatcher/bin/dispatcher dispatch ${{ inputs.pr-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          GITHUB_REPOSITORY: ${{ inputs.repository }}
          WORKFLOW_CONFIG_PATH: shared/workflow-config.yaml

      - name: Report results
        if: always()
        run: |
          echo "📊 Label dispatch completed"
          echo "Repository: ${{ inputs.repository }}"
          echo "PR Number: ${{ inputs.pr-number }}"
          echo "Status: ${{ job.status }}"